---
- name: Build domain list from extravars
  ansible.builtin.set_fact:
    domain_list: "{{ domains | split(',') }}"

- name: Get the first domain
  ansible.builtin.set_fact:
    domain: "{{ domain_list[0] }}"

- name: Build domain list appending
  ansible.builtin.set_fact:
    certbot_domains: "{{ domain_list | map('regex_replace', '^(.*)$', '-d \\1') | join(' ') }}"

- name: Reverse first domain
  ansible.builtin.set_fact:
    reversed_domain: "{{ domain.split('.') | reverse | join('.') }}"

- name: Stop HAProxy
  become: true
  ansible.builtin.systemd:
    name: haproxy
    state: stopped

- name: Get SSL certificates
  become: true
  retries: 3
  ansible.builtin.command:
    cmd: >
      certbot certonly --standalone {{ certbot_domains }} --non-interactive --agree-tos --email
    creates: "/etc/letsencrypt/live/{{ domain }}/fullchain.pem"

- name: Create SSL directory
  become: true
  ansible.builtin.file:
    path: /etc/ssl/{{ reversed_domain }}/
    state: directory
    mode: '0755'

- name: Concatenate SSL certificates
  become: true
  ansible.builtin.shell:
    executable: /bin/bash
    cmd: >
      set -o pipefail && cat /etc/letsencrypt/live/{{ domain }}/fullchain.pem /etc/letsencrypt/live/{{ domain }}/privkey.pem | tee /etc/ssl/{{ reversed_domain }}/{{ reversed_domain }}.pem
    creates: /etc/ssl/{{ reversed_domain }}/{{ reversed_domain }}.pem

- name: Enable HAProxy
  become: true
  ansible.builtin.systemd:
    name: haproxy
    enabled: true
    state: started
