---
- name: Install required packages
  become: yes
  ansible.builtin.apt:
    state: present
    update_cache: yes
    name:
      - ssh
      - cowsay
      - python3-pip
      - htop
      - apt-transport-https
      - ca-certificates
      - software-properties-common
      - gnupg
      - docker.io
      - haproxy
      - certbot
      - net-tools
      - git
      - curl
      - vim
      - netfilter-persistent

- name: Install dependencies
  become: yes
  ansible.builtin.pip:
    state: present
    name:
      - pyyaml
      - docker
      - docker-compose

- name: Setup IPTables
  become: yes
  community.general.iptables:
    chain: INPUT
    jump: ACCEPT
    protocol: tcp
    destination_port:
      - 81
      - 80
      - 443
    state: present

- name: Make iptables rules permanent
  become: yes
  ansible.builtin.shell:
    cmd: netfilter-persistent save

- name: Restart netfilter-persistent service
  become: yes
  ansible.builtin.service:
    name: netfilter-persistent
    state: restarted
