---
- name: Provision K3s
  hosts: master
  remote_user: ubuntu
  gather_facts: true
  roles:
    - role: common
    - role: master
    - role: update
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml

- name: Provision worker
  gather_facts: true
  hosts: worker
  remote_user: ubuntu
  roles:
    - role: common
    - role: worker
    - role: update

- name: Provision Load Balancer
  gather_facts: true
  hosts: lb
  remote_user: ubuntu
  roles:
    - role: lb
    - role: update
  tags:
    load-balancer
