- name: Install required packages
  become: yes
  ansible.builtin.apt:
    state: present
    update_cache: yes
    name:
      - vim
      - curl
      - ssh
      - cowsay
      - git
      - python3-pip
      - htop
      - apt-transport-https
      - ca-certificates
      - software-properties-common
      - gnupg

- name: Install Python dependencies
  become: yes
  ansible.builtin.pip:
    state: present
    name:
      - pyyaml
      - kubernetes
      - docker
      - docker-compose

- name: Download kubectl
  ansible.builtin.get_url:
    url: "https://dl.k8s.io/release/{{ lookup('url', 'https://dl.k8s.io/release/stable.txt') }}/bin/linux/arm64/kubectl"
    dest: /usr/local/bin/kubectl
    mode: '0755'

- name: Disable swap
  become: true
  ansible.builtin.shell: |
    swapoff -a
    sudo sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab

- name: Configure systemd journal
  become: true
  ansible.builtin.lineinfile:
    path: /etc/systemd/journald.conf
    line: "{{ item }}"
    create: yes
  loop:
    - "SystemMaxUse=100M"
    - "SystemMaxFileSize=100M"

- name: Stop and disable netfilter-persistent
  become: true
  ansible.builtin.systemd:
    name: netfilter-persistent
    state: stopped
    enabled: no

- name: Restart systemd-journald
  become: true
  ansible.builtin.systemd:
    name: systemd-journald
    state: restarted
