- name: Install required packages
  become: yes
  ansible.builtin.apt:
    state: present
    update_cache: yes
    name:
      - vim
      - curl
      - ssh
      - cowsay
      - git
      - python3-pip
      - htop
      - apt-transport-https
      - ca-certificates
      - software-properties-common
      - gnupg

- name: Install dependencies
  become: yes
  pip:
    state: present
    name:
      - pyyaml
      - kubernetes
