- name: Install required packages
  become: yes
  ansible.builtin.apt:
    state: present
    update_cache: yes
    name:
      - vim
      - curl
      - ssh
      - cowsay
      - git
      - python3-pip
      - htop
      - apt-transport-https
      - ca-certificates
      - software-properties-common
      - gnupg

- name: Install dependencies
  become: yes
  pip:
    state: present
    name:
      - pyyaml
      - kubernetes
      - docker
      - docker-compose

- name: Install kubectl
  ansible.builtin.get_url:
    url: "https://dl.k8s.io/release/{{ lookup('url', 'https://dl.k8s.io/release/stable.txt') }}/bin/linux/arm64/kubectl"
    dest: /usr/local/bin/kubectl
    mode: '0755'

- name: Setup System
  become: true
  ansible.builtin.shell: |
    swapoff -a
    sudo sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab
    echo "SystemMaxUse=100M" >> /etc/systemd/journald.conf
    echo "SystemMaxFileSize=100M" >> /etc/systemd/journald.conf
    /usr/sbin/netfilter-persistent stop
    /usr/sbin/netfilter-persistent flush
    systemctl stop netfilter-persistent.service
    systemctl disable netfilter-persistent.service
    systemctl restart systemd-journald

