---
- name: Check if ArgoCD is running
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Pod
    namespace: argocd
  register: argocd_pods

- name: Set ArgoCD status
  set_fact:
    argocd_status: "{{ argocd_pods.resources | selectattr('status.phase', 'equalto', 'Running') | list | length > 0 }}"

- name: Add argocd repo to Helm
  kubernetes.core.helm_repository:
    name: argo-cd
    repo_url: https://argoproj.github.io/argo-helm
    state: present
  when: not argocd_status

- name: Clone ArgoCD files repository
  ansible.builtin.git:
    repo: https://github.com/kamuridesu/argocd-apps-test-helm.git
    dest: /tmp/argocd-helm
    clone: yes
    update: yes
  when: not argocd_status

- name: Create istio ingress gateway namespace
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: argocd

- name: Update ArgoCD Helm Chart and Install
  kubernetes.core.helm:
    dependency_update: yes
    chart_ref: /tmp/argocd-helm/charts/argocd
    namespace: argocd
    name: argo-cd
  when: not argocd_status

- name: Install root app
  kubernetes.core.k8s:
    state: present
    src: /tmp/argocd-helm/apps/default.yml
  when: not argocd_status

- name: Remove Helm management over ArgoCD
  kubernetes.core.k8s:
    state: absent
    label_selectors:
      - "owner=helm,name=argo-cd"
    namespace: argocd
    kind: secret
