---
- name: Check if helm exists
  ansible.builtin.shell:
    cmd: which helm
  changed_when: False
  register: helm_status
  failed_when: helm_status.rc != 0 and helm_status.rc != 1

- name: Install helm
  ansible.builtin.shell: |
    curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    chmod 700 get_helm.sh
    ./get_helm.sh
  when: helm_status.rc != 0
