---
- name: Check if helm exists
  ansible.builtin.command:
    cmd: which helm
  changed_when: False
  register: helm_status
  failed_when: helm_status.rc != 0 and helm_status.rc != 1

- name: Download Helm install script
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    dest: /tmp/get_helm.sh
    mode: '0700'
  when: helm_status.rc != 0

- name: Install helm
  ansible.builtin.command: /tmp/get_helm.sh
  when: helm_status.rc != 0
