---
- name: Check if k3s config exists
  ansible.builtin.stat:
    path: /etc/rancher/k3s/k3s.yaml
  register: k3s_config

- name: Install k3s
  ansible.builtin.shell: |
    curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE="644" INSTALL_K3S_EXEC="--disable=traefik --cluster-cidr=192.168.0.0/16 --tls-san "{{ ansible_host }}" --advertise-address "{{ ansible_host }}" --node-external-ip="{{ ansible_host }}"" sh -
    mkdir -p /home/vagrant/.kube
    cp /etc/rancher/k3s/k3s.yaml /home/vagrant/.kube/config
  when: k3s_config.stat.exists == False

- name: Get password on master
  ansible.builtin.shell: cat /var/lib/rancher/k3s/server/node-token
  register: password_output
  run_once: yes

- name: Set password as fact
  set_fact:
    master_password: "{{ password_output.stdout }}"
  run_once: yes


# - include_tasks: calico.yml
# - include_tasks: helm.yml
# - include_tasks: istio.yml
# - include_tasks: argocd.yml
