---
- name: Check if k3s config exists
  ansible.builtin.stat:
    path: /etc/rancher/k3s/k3s.yaml
  register: k3s_config

- name: Get private IP
  ansible.builtin.shell:
    cmd: |
      set -o pipefail;
      hostname -I | cut -d " " -f 1
    executable: /bin/bash
  register: primary_ip_cmd
  changed_when: false

- name: Install k3s
  become: true
  ansible.builtin.shell:
    cmd: |
      set -o pipefail;
      curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE="644" INSTALL_K3S_EXEC="--disable=traefik --cluster-cidr=192.168.0.0/16 --tls-san {{ primary_ip_cmd.stdout }} --tls-san {{ ansible_host }} --advertise-address {{ primary_ip_cmd.stdout }} --node-external-ip={{ ansible_host }}" sh -
    executable: /bin/bash
  when: not k3s_config.stat.exists
  args:
    creates: /etc/rancher/k3s/k3s.yaml

- name: Include Helm tasks
  ansible.builtin.include_tasks: helm.yml

- name: Include ArgoCD tasks
  ansible.builtin.include_tasks: argocd.yml

- name: Include Postgres tasks
  ansible.builtin.include_tasks: postgres.yml
