version: '3.8'
x-postgres-common:
  &postgres-common
  image: postgres:14-alpine
  user: postgres
  restart: always
  healthcheck:
    test: 'pg_isready -U postgres --dbname=postgres'
    interval: 10s
    timeout: 5s
    retries: 5

services:
  postgres_replica:
    <<: *postgres-common
    ports:
      - 5433:5432
    environment:
      PGUSER: replicator
      PGPASSWORD: replicator_password
    command: |
      bash -c "
      grep "k3s" /var/lib/postgresql/data/postgresql.auto.conf || until pg_basebackup --pgdata=/var/lib/postgresql/data -R --slot=replication_slot --host=k3s-cp --port=5432;do echo 'Waiting for primary to connect...';sleep 1s;done
      echo 'Backup done, starting replica...'
      chmod 0700 /var/lib/postgresql/data
      postgres
      "
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: